name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python test_cli_comprehensive.py
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          ## What's Changed
          
          ### Features
          - CLI interface with Rich output
          - Database of deprecated packages
          - Multiple export formats (JSON, YAML, CSV)
          - Scheduler for automatic updates
          - Comprehensive testing suite
          - Complete documentation
          
          ### Installation
          ```bash
          pip install -r requirements.txt
          ```
          
          ### Usage
          ```bash
          # Check project for deprecated dependencies
          python utils/cli.py check --path /path/to/project
          
          # Search for specific package
          python utils/cli.py search requests
          
          # Export database
          python utils/cli.py export-db --format json
          ```
        draft: false
        prerelease: false 