name: Test CLI Interface

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run comprehensive tests
      run: |
        python test_cli_comprehensive.py
    
    - name: Test basic functionality
      run: |
        python utils/cli.py version
        python utils/cli.py stats
        python utils/cli.py search requests
        python utils/cli.py list-db
        python utils/cli.py validate-db
    
    - name: Test project checking
      run: |
        python utils/cli.py check --path test_project
    
    - name: Test exports
      run: |
        python utils/cli.py check --path test_project --export json --output test_report.json
        python utils/cli.py export-db --format json --output db_export.json
        ls -la *.json
    
    - name: Test scheduler
      run: |
        python utils/cli.py scheduler status
        python utils/cli.py clear-cache 